### ISSUE TITLE
test_async_simple_producer flapping?

### ISSUE THREAD

**Issue by dpkp** [mumrah/kafka-python#214]
```
FAIL: test_async_simple_producer (test.test_producer_integration.TestKafkaProducerIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/dpkp/kafka-python/test/testutil.py", line 37, in wrapper
    return func(self)
  File "/home/travis/build/dpkp/kafka-python/test/test_producer_integration.py", line 369, in test_async_simple_producer
    self.assert_fetch_offset(0, start_offset0, [ self.msg("one") ])
  File "/home/travis/build/dpkp/kafka-python/test/test_producer_integration.py", line 412, in assert_fetch_offset
    self.assertEqual(messages, expected_messages)
AssertionError: Lists differ: [] != ['one-test.test_producer_integ...
Second list contains 1 additional elements.
First extra element 0:
one-test.test_producer_integration.TestKafkaProducerIntegration.test_async_simple_producer-419c8aa1-4684-4d20-add6-e6341064e022
- []
+ ['one-test.test_producer_integration.TestKafkaProducerIntegration.test_async_simple_producer-419c8aa1-4684-4d20-add6-e6341064e022']
```

**Comment by dpkp** [comment]
async producer tests should be reliable now
