### ISSUE TITLE
Simple Producer error after topic auto-creation

### ISSUE THREAD

**Issue by jzullo** [mumrah/kafka-python#249]
The SimpleProducer send_messages call will fail with an exception if the Kafka instance it connects to does not have a topic corresponding to the string provided as the topic in the function call. Topic auto-creation suceeds, but the message is not logged. A subsequent run of the script will log the message, but catching the exception and resending will fail with the original exception.

Reproduction steps:
Create a KafkaClient, and a SimpleProducer using the KafkaClient.
Send a message to a non-existent topic.
Expected Results: The message is sent, the topic creates, and the message is logged
Actual Results: The message is sent, the topic creates, and the script fails with a kafka.common.LeaderNotAvailableError exception.

This issue occurs when using the latest code from master. When I used the previous release, I was receiving an UnknownTopicOrPartitionError(topic) exception instead.

kafka-python version: master
Kafka version: kafka/0.8.1.1/kafka_2.9.2-0.8.1.1
Zookeeper version: 3.4.6

Script:
```python
from __future__ import absolute_import
from kafka import KafkaClient, SimpleProducer

class Message(object):
    def __init__(self, topic, message):
        self.topic = topic
        self.message = message

    def send(self):
        kafka = KafkaClient("localhost:9092")
        producer = SimpleProducer(kafka)
        producer.send_messages(self.topic, self.message)

message = Message('abcd-test', 'test message')
message.send()
```
Run 1 output (client):
Traceback (most recent call last):
  File "message.py", line 18, in <module>
    message.send();
  File "message.py", line 15, in send
    producer.send_messages(self.topic, self.message)
  File "build/bdist.linux-x86_64/egg/kafka/producer/simple.py", line 69, in send_messages
  File "build/bdist.linux-x86_64/egg/kafka/producer/simple.py", line 56, in _next_partition
  File "build/bdist.linux-x86_64/egg/kafka/client.py", line 323, in load_metadata_for_topics
  File "build/bdist.linux-x86_64/egg/kafka/common.py", line 215, in check_error
kafka.common.LeaderNotAvailableError: TopicMetadata(topic='abcd-test', error=5, partitions=[])

Run 1 output (Kafka):
[2014-09-29 18:41:14,761] INFO Topic creation {"version":1,"partitions":{"0":[1]}} (kafka.admin.AdminUtils$)
[2014-09-29 18:41:14,765] INFO [KafkaApi-1] Auto creation of topic abcd-test with 1 partitions and replication factor 1 is successful! (kafka.server.KafkaApis)
[2014-09-29 18:41:14,778] INFO Closing socket connection to /10.0.2.2. (kafka.network.Processor)
[2014-09-29 18:41:14,792] INFO [ReplicaFetcherManager on broker 1] Removed fetcher for partitions [abcd-test,0] (kafka.server.ReplicaFetcherManager)
[2014-09-29 18:41:14,810] INFO Completed load of log abcd-test-0 with log end offset 0 (kafka.log.Log)
[2014-09-29 18:41:14,813] INFO Created log for partition [abcd-test,0] in /tmp/kafka-logs with properties {segment.index.bytes -> 10485760, file.delete.delay.ms -> 60000, segment.bytes -> 536870912, flush.ms -> 1000, delete.retention.ms -> 86400000, index.interval.bytes -> 4096, retention.bytes -> -1, cleanup.policy -> delete, segment.ms -> 604800000, max.message.bytes -> 1000012, flush.messages -> 10000, min.cleanable.dirty.ratio -> 0.5, retention.ms -> 604800000}. (kafka.log.LogManager)
[2014-09-29 18:41:14,814] WARN Partition [abcd-test,0] on broker 1: No checkpointed highwatermark is found for partition [abcd-test,0] (kafka.cluster.Partition)

Run 2 output (client):
none (message submits successfully

Run 2 output (Kafka):
[2014-09-29 18:41:19,897] INFO Closing socket connection to /10.0.2.2. (kafka.network.Processor)

**Comment by dpkp** [comment]
you've got it -- try/except and catch the `LeaderNotAvailableError`.  Creating a topic does take a short amount of time, so the first attempt to produce a message to a new topic using auto-create will fail and you will need to sleep briefly and retry.

**Comment by joshuarichard** [comment]
I know this ticket is closed, but can anything else cause this issue? I've tried both workarounds I've found, wrapping send_messages() in a try/except and putting ensure_topic_exists() at the front of my code. Running kafka 0.8.2 and zookeeper 3.4.6 in docker containers with latest kafka-python pull.

**Comment by dpkp** [comment]
If you are getting the LeaderNotAvailable exception unexpectedly, the best place to start is to check for more information in your kafka server logs.

For kafka-python, you might consider switching to the async producer. It should be much more reliable as of the latest kafka-python release, and it will handle retries internally.

**Comment by movermeyer** [comment]
@joshuarichard, I was having LeaderNotAvailable happen persistently even well after it had created the topic. In my case, it was a result of having set "advertised.host.name" incorrectly (typo).
