### ISSUE TITLE
Update documentation re bytes topics/messages when using python 3

### ISSUE THREAD

**Issue by bplus** [mumrah/kafka-python#251]
Hello, 

As I use python 3.3, I'm looking for any info on when the next scheduled release will be.  Is there anything planned right now?

Thanks in advance for any information.

**Comment by sontek** [comment]
Any update on when a python 3 compatibility release will happen?

**Comment by dpkp** [comment]
I expect we will cut a new release off master as soon as kafka 0.8.2 goes final.

**Comment by dpkp** [comment]
python3 is supported as of version 0.9.3. further documentation is available at http://kafka-python.readthedocs.org/en/latest/

**Comment by parag4code** [comment]
`Traceback (most recent call last):
  File "producer.py", line 3, in <module>
    client=KafkaClient('localhost:9000')
  File "/home/parag/.local/lib/python2.7/site-packages/kafka/__init__.py", line 41, in __init__
    super(KafkaClient, self).__init__(*args, **kwargs)
  File "/home/parag/.local/lib/python2.7/site-packages/kafka/client.py", line 53, in __init__
    self.load_metadata_for_topics()  # bootstrap with all metadata
  File "/home/parag/.local/lib/python2.7/site-packages/kafka/client.py", line 523, in load_metadata_for_topics
    resp = self.send_metadata_request(topics)
  File "/home/parag/.local/lib/python2.7/site-packages/kafka/client.py", line 588, in send_metadata_request
    return self._send_broker_unaware_request(payloads, encoder, decoder)
  File "/home/parag/.local/lib/python2.7/site-packages/kafka/client.py", line 182, in _send_broker_unaware_request
    raise KafkaUnavailableError('All servers failed to process request: %s' % hosts)
kafka.errors.KafkaUnavailableError: All servers failed to process request: [('localhost', 9000, 0)]
`
Can anyone suggest why am in not able to connect ?
