### ISSUE TITLE
error running example.py

### ISSUE THREAD

**Issue by alecinvan** [mumrah/kafka-python#349]
Hi, 

I installed Kafka-python, but failed in some unit test:

  lint: commands succeeded
ERROR:   py26: InterpreterNotFound: python2.6
  py27: commands succeeded
ERROR:   pypy: could not install deps [six, unittest2, nose, nose-timer, coverage, mock, python-snappy]
ERROR:   py33: InterpreterNotFound: python3.3
  py34: commands succeeded
  docs: commands succeeded

Next step, I run the example.py, it did send message and consumer messages, but getting such error:
2015-03-20 12:01:16,116.116.296052933:kafka:140525348022016:DEBUG:16263:Read 36/36 bytes from Kafka
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "example.py", line 27, in run
    consumer = SimpleConsumer(client, "test-group", "my-topic")
  File "/home/stuser/RESTClients/kafka-python/kafka/consumer/simple.py", line 123, in __init__
    auto_commit_every_t=auto_commit_every_t)
  File "/home/stuser/RESTClients/kafka-python/kafka/consumer/base.py", line 71, in __init__
    self.fetch_last_known_offsets(partitions)
  File "/home/stuser/RESTClients/kafka-python/kafka/consumer/base.py", line 91, in fetch_last_known_offsets
    self.offsets[partition] = get_or_init_offset(resp)
  File "/home/stuser/RESTClients/kafka-python/kafka/consumer/base.py", line 82, in get_or_init_offset
    kafka.common.check_error(resp)
  File "/home/stuser/RESTClients/kafka-python/kafka/common.py", line 217, in check_error
    raise error_class(response)
UnknownError: OffsetFetchResponse(topic='my-topic', partition=0, offset=-1, metadata='', error=16)

Load_example generates such errors:
Messages sent: 686
Traceback (most recent call last):
  File "load_example.py", line 60, in <module>
    main()
  File "load_example.py", line 52, in main
    print 'Messages recvd: %d' % threads[1].valid
AttributeError: 'Consumer' object has no attribute 'valid'

Any ideas?

thanks
AL

**Comment by dpkp** [comment]
what version of kafka-python and what version of kafka server?

api error 16 is `NotCoordinatorForConsumerCode` (see https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-ErrorCodes)

That api is new in 0.8.2 servers and is broken in the beta. So if you are using 0.8.2-beta, then you should upgrade the server to the released version because the beta is known to fail w/ kafka-python.

**Comment by dpkp** [comment]
Please reopen if the above suggestion did not solve your issue!

**Comment by huhongbo** [comment]
seems 0.8.2 has the same problem
