### ISSUE TITLE
Consumer does not handle exceptions in commit()

### ISSUE THREAD

**Issue by saiwl** [mumrah/kafka-python#371]
my kafka version supports the auto-commit option,as the title shows,i already received messages after auto-commit setting true.But i still get the error below after receiving several messages:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.6/threading.py", line 484, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.6/site-packages/kafka/util.py", line 134, in _timer
    self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python2.6/site-packages/kafka/consumer/base.py", line 127, in commit
    resps = self.client.send_offset_commit_request(self.group, reqs)
  File "/usr/lib/python2.6/site-packages/kafka/client.py", line 474, in send_offset_commit_request
    resps = self._send_broker_aware_request(payloads, encoder, decoder)
  File "/usr/lib/python2.6/site-packages/kafka/client.py", line 202, in _send_broker_aware_request
    raise FailedPayloadsError(failed_payloads)
FailedPayloadsError: [OffsetCommitRequest(topic='syslog', partition=0, offset=34690, metadata=None)]

can you help me?
thanks a lot!

**Comment by dpkp** [comment]
what is your kafka server version?  what is your kafka-pythoh version? can you paste the code you are using to run your consumer ?

FailedPayloadsError is a generic failure that could either mean there were network problems, or it could mean that the server closed the socket abruptly, which the current kafka server will do when it doesn't recognize a request or otherwise the request processing raised an unhandled server exception.
