### ISSUE TITLE
kafka.common.FailedPayloadsError while invoking send_offset_request

### ISSUE THREAD

**Issue by unklhe** [mumrah/kafka-python#470]
My kafka server is running in an EC2 who has a public IP and private domain name, which means user could access the kafka service via IP, but not domain name. When I init the kafka consumer I get an error. 
**My code:**
```python
from kafka import KafkaConsumer
consumer = KafkaConsumer("mytopic",  bootstrap_servers="10.x.x.x:9092")
```
**Error:**
Traceback (most recent call last):
  File "tools\flow.py", line 46, in <module>
    + ":" + global_vars.Configuration["kafka"]["port"]])
  File "C:\Apps\Python27\lib\site-packages\kafka\consumer\kafka.py", line 59, in __init__
    self.set_topic_partitions(*topics)
  File "C:\Apps\Python27\lib\site-packages\kafka\consumer\kafka.py", line 260, in set_topic_partitions
    self._offsets.fetch[topic_partition] = self._reset_partition_offset(topic_partition)
  File "C:\Apps\Python27\lib\site-packages\kafka\consumer\kafka.py", line 667, in _reset_partition_offset
    request_time_ms, max_num_offsets=1)
  File "C:\Apps\Python27\lib\site-packages\kafka\consumer\kafka.py", line 425, in get_partition_offsets
    (resp,) = self._client.send_offset_request(reqs)
  File "C:\Apps\Python27\lib\site-packages\kafka\client.py", line 510, in send_offset_request
    if not fail_on_error or not self._raise_on_response_error(resp)]
  File "C:\Apps\Python27\lib\site-packages\kafka\client.py", line 247, in _raise_on_response_error
    raise resp
kafka.common.FailedPayloadsError

After adding logging handle get below log:
Unable to connect to kafka broker at ip-x-x-x-x:9092
Traceback (most recent call last):
  File "C:\Apps\Python27\lib\site-packages\kafka\conn.py", line 211, in reinit
    self._sock = socket.create_connection((self.host, self.port), self.timeout)
  File "C:\Apps\Python27\lib\socket.py", line 571, in create_connection
    raise err
error: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
ConnectionError attempting to send request 3 to server BrokerMetadata(nodeId=0, host='ip-x-x-x-x', port=9092): Kafka @ ip-x-x-x-x:9092 went away

So here I see IP is translated to domain name which causes the upcoming access to Kafka failed.

**Comment by unklhe** [comment]
Finally I found it's because broker is listening on hostname, not 0.0.0.0 . After changing to 0.0.0.0 it works. So close this issue.
