### ISSUE TITLE
Exception 'i' format requires -2147483648 <= number <= 2147483647

### ISSUE THREAD

**Issue by joefremont** [mumrah/kafka-python#86]
We are having some problems where our process reads from a kafka queue.  It read for a while and then gets the following exception.  Only solution we have so far is to export the queue data using the command line client, shut down kafka and zookeeper, delete the queue and then restart and re-import the queue data.

***********************************************
Exception
'i' format requires -2147483648 <= number <= 2147483647
Traceback (most recent call last):
  File "/home/socialtracker/SocialTracking/common/basedaemon.py", line 115, in run
    for message in consumer:
  File "/home/socialtracker/SocialTracking/env/local/lib/python2.7/site-packages/kafka/consumer.py", line 329, in __iter__
    yield (partition, it.next())
  File "/home/socialtracker/SocialTracking/env/local/lib/python2.7/site-packages/kafka/consumer.py", line 372, in __iter_partition__
    min_bytes=fetch_size)
  File "/home/socialtracker/SocialTracking/env/local/lib/python2.7/site-packages/kafka/client.py", line 277, in send_fetch_request
    KafkaProtocol.decode_fetch_response)
  File "/home/socialtracker/SocialTracking/env/local/lib/python2.7/site-packages/kafka/client.py", line 166, in _send_broker_aware_request
    correlation_id=requestId, payloads=payloads)
  File "/home/socialtracker/SocialTracking/env/local/lib/python2.7/site-packages/kafka/protocol.py", line 249, in encode_fetch_request
    len(grouped_payloads))
error: 'i' format requires -2147483648 <= number <= 2147483647
None

**Comment by dpkp** [comment]
pls reopen if this issue still affects the latest kafka-python release
